export const MAIN_PAGE = '/';
export const BASE_URL = 'http://localhost:3000/';
export const REVERSE_STRING_PAGE = '/recursion';
export const FIBONACCI_PAGE = '/fibonacci';
export const SORTING_PAGE = '/sorting';
export const STACK_PAGE = '/stack';
export const QUEUE_PAGE = '/queue';
export const LIST_PAGE = '/list';
export const BUTTON_REVERSE_STRING = '[data-testid="button"]';
export const BUTTON_FIBONACCI = '[data-testid="button"]';
export const INPUT_REVERSE_STRING = 'input';
export const INPUT_FIBONACCI = 'input';
export const REVERSE_STRING_ID = '[data-testid="recursion"]';
export const FIBONACCI_ID = '[data-testid="fibonacci"]';
export const SORTING_ID = '[data-testid="sorting"]';
export const STACK_ID = '[data-testid="stack"]';
export const QUEUE_ID = '[data-testid="queue"]';
export const LIST_ID = '[data-testid="list"]';
export const CIRCLE = '[class^="circle_content__"]';
export const CIRCLE_BORDER = '[class^="circle_circle__"]';
export const CIRCLE_MODIFIED_STYLE = '4px solid rgb(127, 224, 81)';
export const CIRCLE_DEFAULT_STYLE = '4px solid rgb(0, 50, 255)';
export const CIRCLE_CHANGING_STYLE = '4px solid rgb(210, 82, 225)';
export const CIRCLE_INDEX = '[class*="circle_index__"]';
